### ISSUE TITLE
CentOS 7.6 CMake Error: CMake 3.1 or higher is required

### ISSUE THREAD

**Issue by ZJUguquan** [Xtra-Computing/thundergbm#11]
Hi, sorry for bothering you all again.

I have installed thundergbm via **pip** on windows 8.1 before and it succeed. This time I install it on linux(CentOS 7.6) but some problems occur.

- When I install via **pip**, it succeed. But when I import it, the error is:
![image](https://user-images.githubusercontent.com/19544736/55450138-c369f280-5600-11e9-8d32-888812160c60.png)

- So I try to build it via **CMake**. However, there are still errors saying:
![image](https://user-images.githubusercontent.com/19544736/55450224-02984380-5601-11e9-8b0b-a3bbd9d6e3a5.png)

- It's strange because it requires higher CMake version but on the **Readme.md** it says:
![image](https://user-images.githubusercontent.com/19544736/55450571-3a53bb00-5602-11e9-8be4-3fddf1ca9eea.png)

My environment：
- gcc 4.8.5
- cmake 2.8.12.2
- cuda 9.0
- CentOS 7.6.1810

Wating for your advice. Thanks~

**Comment by jiahuanluo** [comment]
Dear Quan Gu,

Thanks for your kindly informing.

I have updated the [CMakeLists.txt](https://github.com/Xtra-Computing/thundergbm/blob/master/CMakeLists.txt) and released a new version thundergbm to PYPI, you can use `pip install -U thundergbm` to update your package.

Currently ThunderGBM installed via **pip** only supports CUDA 9.0, because CUDA 10 is liminted to CUDA driver version >=410.48. Therefore if you want to use ThunderGBM, you can build it yourself.

Best regards,
Jiahuan Luo
